# Generated by Django 3.0.5 on 2020-04-23 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StockApp',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('symbol', models.TextField(blank=True, db_column='Symbol', null=True)),
                ('dates', models.TextField(blank=True, null=True)),
                ('consolidated_income', models.BigIntegerField(blank=True, db_column='Consolidated Income', null=True)),
                ('cost_of_revenue', models.BigIntegerField(blank=True, db_column='Cost of Revenue', null=True)),
                ('dividend_per_share', models.BigIntegerField(blank=True, db_column='Dividend per Share', null=True)),
                ('ebit', models.BigIntegerField(blank=True, db_column='EBIT', null=True)),
                ('ebit_margin', models.BigIntegerField(blank=True, db_column='EBIT Margin', null=True)),
                ('ebitda', models.BigIntegerField(blank=True, db_column='EBITDA', null=True)),
                ('ebitda_margin', models.BigIntegerField(blank=True, db_column='EBITDA Margin', null=True)),
                ('eps', models.BigIntegerField(blank=True, db_column='EPS', null=True)),
                ('eps_diluted', models.BigIntegerField(blank=True, db_column='EPS Diluted', null=True)),
                ('earnings_before_tax_margin', models.BigIntegerField(blank=True, db_column='Earnings Before Tax Margin', null=True)),
                ('earnings_before_tax', models.BigIntegerField(blank=True, db_column='Earnings before Tax', null=True)),
                ('free_cash_flow_margin', models.BigIntegerField(blank=True, db_column='Free Cash Flow margin', null=True)),
                ('gross_margin', models.BigIntegerField(blank=True, db_column='Gross Margin', null=True)),
                ('gross_profit', models.BigIntegerField(blank=True, db_column='Gross Profit', null=True)),
                ('income_tax_expense', models.BigIntegerField(blank=True, db_column='Income Tax Expense', null=True)),
                ('interest_expense', models.BigIntegerField(blank=True, db_column='Interest Expense', null=True)),
                ('net_income', models.BigIntegerField(blank=True, db_column='Net Income', null=True)),
                ('net_income_discontinued_ops', models.BigIntegerField(blank=True, db_column='Net Income - Discontinued ops', null=True)),
                ('net_income_non_controlling_int', models.BigIntegerField(blank=True, db_column='Net Income - Non-Controlling int', null=True)),
                ('net_income_com', models.BigIntegerField(blank=True, db_column='Net Income Com', null=True)),
                ('net_profit_margin', models.BigIntegerField(blank=True, db_column='Net Profit Margin', null=True)),
                ('operating_expenses', models.BigIntegerField(blank=True, db_column='Operating Expenses', null=True)),
                ('operating_income', models.BigIntegerField(blank=True, db_column='Operating Income', null=True)),
                ('preferred_dividends', models.BigIntegerField(blank=True, db_column='Preferred Dividends', null=True)),
                ('profit_margin', models.BigIntegerField(blank=True, db_column='Profit Margin', null=True)),
                ('r_d_expenses', models.BigIntegerField(blank=True, db_column='R&D Expenses', null=True)),
                ('revenue', models.BigIntegerField(blank=True, db_column='Revenue', null=True)),
                ('revenue_growth', models.BigIntegerField(blank=True, db_column='Revenue Growth', null=True)),
                ('sg_a_expense', models.BigIntegerField(blank=True, db_column='SG&A Expense', null=True)),
                ('weighted_avg_shs_out', models.BigIntegerField(blank=True, db_column='Weighted Avg Shs Out', null=True)),
                ('weighted_average_shs_out_dil', models.BigIntegerField(blank=True, db_column='Weighted Average Shs Out_Dil', null=True)),
            ],
            options={
                'db_table': 'financials',
                'managed': True,
            },
        ),
    ]
