# Generated by Django 3.0.5 on 2020-05-01 22:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trends', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='stockapp',
            table='financials_data',
        ),
    ]
